

% Latex  settings
set(gca,'TickLabelInterpreter', 'latex');
set(gca,...
        'Units','normalized',...
        'FontUnits','points',...
        'FontWeight','normal',...
        'FontSize',40,...
        'FontName','Times');
