    
    %%
       
    cd Results/
        
    buf_P1 = sprintf('********* \n MFC :: \n SSE = %f \n  STD = %f \n ********* \n AST :: \n SSE = %f \n  STD = %f \n ********* \n PIDa :: \n SSE = %f \n  STD = %f \n ********* \n PIDb :: \n SSE = %f \n  STD = %f \n ********* \n PIDc :: \n SSE = %f \n  STD = %f \n ********* \n', ...
        Stat_SSE_seg(index_scenario,1).S1, ...
        Stat_STD_seg(index_scenario,1).S1, ...
        ...
        Stat_SSE_seg(index_scenario,2).S1, ...
        Stat_STD_seg(index_scenario,2).S1, ...
        ...
        Stat_SSE_seg(index_scenario,3).S1, ...
        Stat_STD_seg(index_scenario,3).S1, ...
        ...
        Stat_SSE_seg(index_scenario,4).S1, ...
        Stat_STD_seg(index_scenario,4).S1, ...
        ...
        Stat_SSE_seg(index_scenario,5).S1, ...
        Stat_STD_seg(index_scenario,5).S1);
    
    
    buf_P2 = sprintf('********* \n MFC :: \n SSE = %f \n  STD = %f \n ********* \n AST :: \n SSE = %f \n  STD = %f \n ********* \n PIDa :: \n SSE = %f \n  STD = %f \n ********* \n PIDb :: \n SSE = %f \n  STD = %f \n ********* \n PIDc :: \n SSE = %f \n  STD = %f \n ********* \n', ...
        Stat_SSE_seg(index_scenario,1).S2, ...
        Stat_STD_seg(index_scenario,1).S2, ...
        ...
        Stat_SSE_seg(index_scenario,2).S2, ...
        Stat_STD_seg(index_scenario,2).S2, ...
        ...
        Stat_SSE_seg(index_scenario,3).S2, ...
        Stat_STD_seg(index_scenario,3).S2, ...
        ...
        Stat_SSE_seg(index_scenario,4).S2, ...
        Stat_STD_seg(index_scenario,4).S2, ...
        ...
        Stat_SSE_seg(index_scenario,5).S2, ...
        Stat_STD_seg(index_scenario,5).S2);
    
    
    buf_P3 = sprintf('********* \n MFC :: \n SSE = %f \n  STD = %f \n ********* \n AST :: \n SSE = %f \n  STD = %f \n ********* \n PIDa :: \n SSE = %f \n  STD = %f \n ********* \n PIDb :: \n SSE = %f \n  STD = %f \n ********* \n PIDc :: \n SSE = %f \n  STD = %f \n ********* \n', ...
        Stat_SSE_seg(index_scenario,1).S3, ...
        Stat_STD_seg(index_scenario,1).S3, ...
        ...
        Stat_SSE_seg(index_scenario,2).S3, ...
        Stat_STD_seg(index_scenario,2).S3, ...
        ...
        Stat_SSE_seg(index_scenario,3).S3, ...
        Stat_STD_seg(index_scenario,3).S3, ...
        ...
        Stat_SSE_seg(index_scenario,4).S3, ...
        Stat_STD_seg(index_scenario,4).S3, ...
        ...
        Stat_SSE_seg(index_scenario,5).S3, ...
        Stat_STD_seg(index_scenario,5).S3);
    
    
    buf_P4 = sprintf('********* \n MFC :: \n SSE = %f \n  STD = %f \n ********* \n AST :: \n SSE = %f \n  STD = %f \n ********* \n PIDa :: \n SSE = %f \n  STD = %f \n ********* \n PIDb :: \n SSE = %f \n  STD = %f \n ********* \n PIDc :: \n SSE = %f \n  STD = %f \n ********* \n', ...
        Stat_SSE_seg(index_scenario,1).S4, ...
        Stat_STD_seg(index_scenario,1).S4, ...
        ...
        Stat_SSE_seg(index_scenario,2).S4, ...
        Stat_STD_seg(index_scenario,2).S4, ...
        ...
        Stat_SSE_seg(index_scenario,3).S4, ...
        Stat_STD_seg(index_scenario,3).S4, ...
        ...
        Stat_SSE_seg(index_scenario,4).S4, ...
        Stat_STD_seg(index_scenario,4).S4, ...
        ...
        Stat_SSE_seg(index_scenario,5).S4, ...
        Stat_STD_seg(index_scenario,5).S4);
    
    
    if ( length( StatSegment(index_scenario,1).Seg_temps_1 == StatSegment(index_scenario,1).Seg_temps_2 ) ...
      && length( StatSegment(index_scenario,1).Seg_temps_2 == StatSegment(index_scenario,1).Seg_temps_3 ) ...
      && length( StatSegment(index_scenario,1).Seg_temps_3 == StatSegment(index_scenario,1).Seg_temps_4 ) )
        fprintf('OK to plot... \n')
    else

        fprintf('problem')
        pa
    end


    %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    buffer_title = sprintf("Sc #%d-- LengthPts %d", index_scenario, length( StatSegment(index_scenario,1).Seg_temps_1 ) );

    % P_1
    save_ = sprintf( buffer_title + '_P1.png' );

    figure(1000)
    figure('units','normalized','outerposition',[0 0 1 1])
    hold on
    plot( StatSegment(index_scenario,1).Seg_temps_1, StatSegment(index_scenario,1).P1_y - StatSegment(index_scenario,1).P1_reference(1), 'linewidth', 2)    ;
    plot( StatSegment(index_scenario,1).Seg_temps_1, StatSegment(index_scenario,2).P1_y - StatSegment(index_scenario,2).P1_reference(1), 'linewidth', 2)    ;
    plot( StatSegment(index_scenario,1).Seg_temps_1, StatSegment(index_scenario,3).P1_y - StatSegment(index_scenario,3).P1_reference(1), 'linewidth', 2)    ;
    plot( StatSegment(index_scenario,1).Seg_temps_1, StatSegment(index_scenario,4).P1_y - StatSegment(index_scenario,4).P1_reference(1), 'linewidth', 2)    ;
    plot( StatSegment(index_scenario,1).Seg_temps_1, StatSegment(index_scenario,5).P1_y - StatSegment(index_scenario,5).P1_reference(1), 'linewidth', 2)    ;
     annotation('textbox',[.9 .5 .1 .2], ...
         'String',buf_P1,'EdgeColor','none', 'FontSize',15);
    xlabel('Time [s]','Interpreter','latex','FontSize',40);
    ylabel('F [N]','Interpreter','latex','FontSize',40);
    legend("MFC", "STW", "PIDa", "PIDb", "PIDc");
    title(buffer_title)
    set(gcf,'Color','w');
    set(gca,'FontSize',40);
    saveas(gcf,save_,'png')

    length( StatSegment(index_scenario,1).Seg_temps_1 )
    
    % P_2
    save_ = sprintf(buffer_title + '_P2.png' );

    figure(1001)
    figure('units','normalized','outerposition',[0 0 1 1])
    hold on
    plot( StatSegment(index_scenario,1).Seg_temps_2, StatSegment(index_scenario,1).P2_y - StatSegment(index_scenario,1).P2_reference(1), 'linewidth', 2)    ;
    plot( StatSegment(index_scenario,1).Seg_temps_2, StatSegment(index_scenario,2).P2_y - StatSegment(index_scenario,2).P2_reference(1), 'linewidth', 2)    ;
    plot( StatSegment(index_scenario,1).Seg_temps_2, StatSegment(index_scenario,3).P2_y - StatSegment(index_scenario,3).P2_reference(1), 'linewidth', 2)    ;
    plot( StatSegment(index_scenario,1).Seg_temps_2, StatSegment(index_scenario,4).P2_y - StatSegment(index_scenario,4).P2_reference(1), 'linewidth', 2)    ;
    plot( StatSegment(index_scenario,1).Seg_temps_2, StatSegment(index_scenario,5).P2_y - StatSegment(index_scenario,5).P2_reference(1), 'linewidth', 2)    ;
         annotation('textbox',[.9 .5 .1 .2], ...
         'String',buf_P2,'EdgeColor','none', 'FontSize',15);
    xlabel('Time [s]','Interpreter','latex','FontSize',40);
    ylabel('F [N]','Interpreter','latex','FontSize',40);
    legend("MFC", "STW", "PIDa", "PIDb", "PIDc");
    title(buffer_title)
    set(gcf,'Color','w');
    set(gca,'FontSize',40);
    saveas(gcf,save_,'png')

    length( StatSegment(index_scenario,1).Seg_temps_2 )

    % P_3
    save_ = sprintf( buffer_title + '_P3.png' );

    figure(1002)
    figure('units','normalized','outerposition',[0 0 1 1])
    hold on
    plot( StatSegment(index_scenario,1).Seg_temps_3, StatSegment(index_scenario,1).P3_y - StatSegment(index_scenario,1).P3_reference(1), 'linewidth', 2)    ;
    plot( StatSegment(index_scenario,1).Seg_temps_3, StatSegment(index_scenario,2).P3_y - StatSegment(index_scenario,2).P3_reference(1), 'linewidth', 2)    ;
    plot( StatSegment(index_scenario,1).Seg_temps_3, StatSegment(index_scenario,3).P3_y - StatSegment(index_scenario,3).P3_reference(1), 'linewidth', 2)    ;
    plot( StatSegment(index_scenario,1).Seg_temps_3, StatSegment(index_scenario,4).P3_y - StatSegment(index_scenario,4).P3_reference(1), 'linewidth', 2)    ;
    plot( StatSegment(index_scenario,1).Seg_temps_3, StatSegment(index_scenario,5).P3_y - StatSegment(index_scenario,5).P3_reference(1), 'linewidth', 2)    ;
         annotation('textbox',[.9 .5 .1 .2], ...
         'String',buf_P3,'EdgeColor','none', 'FontSize',15);
    xlabel('Time [s]','Interpreter','latex','FontSize',40);
    ylabel('F [N]','Interpreter','latex','FontSize',40);
    legend("MFC", "STW", "PIDa", "PIDb", "PIDc");
    title(buffer_title)
    set(gcf,'Color','w');
    set(gca,'FontSize',40);
    saveas(gcf,save_,'png')

    length( StatSegment(index_scenario,1).Seg_temps_3 )

    % P_4
    save_ = sprintf( buffer_title + '_P4.png' );

    figure(1003)
    figure('units','normalized','outerposition',[0 0 1 1])
    hold on
    plot( StatSegment(index_scenario,1).Seg_temps_4, StatSegment(index_scenario,1).P4_y - StatSegment(index_scenario,1).P4_reference(1), 'linewidth', 2)     ;
    plot( StatSegment(index_scenario,1).Seg_temps_4, StatSegment(index_scenario,2).P4_y - StatSegment(index_scenario,2).P4_reference(1), 'linewidth', 2)     ;
    plot( StatSegment(index_scenario,1).Seg_temps_4, StatSegment(index_scenario,3).P4_y - StatSegment(index_scenario,3).P4_reference(1), 'linewidth', 2)     ;
    plot( StatSegment(index_scenario,1).Seg_temps_4, StatSegment(index_scenario,4).P4_y - StatSegment(index_scenario,4).P4_reference(1), 'linewidth', 2)     ;
    plot( StatSegment(index_scenario,1).Seg_temps_4, StatSegment(index_scenario,5).P4_y - StatSegment(index_scenario,5).P4_reference(1), 'linewidth', 2)     ;
         annotation('textbox',[.9 .5 .1 .2], ...
         'String',buf_P4,'EdgeColor','none', 'FontSize',15);
    xlabel('Time [s]','Interpreter','latex','FontSize',40);
    ylabel('F [N]','Interpreter','latex','FontSize',40);
    legend("MFC", "STW", "PIDa", "PIDb", "PIDc");
    title(buffer_title)
    set(gcf,'Color','w');
    set(gca,'FontSize',40);
    saveas(gcf,save_,'png')

    length( StatSegment(index_scenario,1).Seg_temps_4 )


    close all
    
    cd ..

    % end of the script
